# Generated by Django 3.2.4 on 2021-08-22 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210822_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
